/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Com.Hopper.Hts.Airlines.Client.OpenAPIDateConverter;

namespace Com.Hopper.Hts.Airlines.Model
{
    /// <summary>
    /// A create DG contract request
    /// </summary>
    [DataContract(Name = "create_dg_contract_request")]
    public partial class CreateDgContractRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDgContractRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateDgContractRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDgContractRequest" /> class.
        /// </summary>
        /// <param name="offerIds">Identifier of the offer(s) for which the contract is created (required).</param>
        /// <param name="itinerary">itinerary (required).</param>
        /// <param name="extAttributes">extAttributes (required).</param>
        /// <param name="pnrReference">Reference of the PNR in the airline system.</param>
        public CreateDgContractRequest(List<string> offerIds = default(List<string>), DgItinerary itinerary = default(DgItinerary), Dictionary<string, string> extAttributes = default(Dictionary<string, string>), string pnrReference = default(string))
        {
            // to ensure "offerIds" is required (not null)
            if (offerIds == null)
            {
                throw new ArgumentNullException("offerIds is a required property for CreateDgContractRequest and cannot be null");
            }
            this.OfferIds = offerIds;
            // to ensure "itinerary" is required (not null)
            if (itinerary == null)
            {
                throw new ArgumentNullException("itinerary is a required property for CreateDgContractRequest and cannot be null");
            }
            this.Itinerary = itinerary;
            // to ensure "extAttributes" is required (not null)
            if (extAttributes == null)
            {
                throw new ArgumentNullException("extAttributes is a required property for CreateDgContractRequest and cannot be null");
            }
            this.ExtAttributes = extAttributes;
            this.PnrReference = pnrReference;
        }

        /// <summary>
        /// Identifier of the offer(s) for which the contract is created
        /// </summary>
        /// <value>Identifier of the offer(s) for which the contract is created</value>
        /*
        <example>1ec9eed3-4486-6460-9d6c-2fb8469d35db</example>
        */
        [DataMember(Name = "offer_ids", IsRequired = true, EmitDefaultValue = true)]
        public List<string> OfferIds { get; set; }

        /// <summary>
        /// Gets or Sets Itinerary
        /// </summary>
        [DataMember(Name = "itinerary", IsRequired = true, EmitDefaultValue = true)]
        public DgItinerary Itinerary { get; set; }

        /// <summary>
        /// Gets or Sets ExtAttributes
        /// </summary>
        [DataMember(Name = "ext_attributes", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, string> ExtAttributes { get; set; }

        /// <summary>
        /// Reference of the PNR in the airline system
        /// </summary>
        /// <value>Reference of the PNR in the airline system</value>
        /*
        <example>ABC123</example>
        */
        [DataMember(Name = "pnr_reference", EmitDefaultValue = false)]
        public string PnrReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateDgContractRequest {\n");
            sb.Append("  OfferIds: ").Append(OfferIds).Append("\n");
            sb.Append("  Itinerary: ").Append(Itinerary).Append("\n");
            sb.Append("  ExtAttributes: ").Append(ExtAttributes).Append("\n");
            sb.Append("  PnrReference: ").Append(PnrReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
