/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Com.Hopper.Hts.Airlines.Client.OpenAPIDateConverter;

namespace Com.Hopper.Hts.Airlines.Model
{
    /// <summary>
    /// An object containing exercise information for a contract
    /// </summary>
    [DataContract(Name = "dg_customer_create_contract_exercise_response")]
    public partial class DgCustomerCreateContractExerciseResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DgCustomerCreateContractExerciseResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DgCustomerCreateContractExerciseResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DgCustomerCreateContractExerciseResponse" /> class.
        /// </summary>
        /// <param name="exerciseId">Unique identifier for a DG exercise (required).</param>
        public DgCustomerCreateContractExerciseResponse(string exerciseId = default(string))
        {
            // to ensure "exerciseId" is required (not null)
            if (exerciseId == null)
            {
                throw new ArgumentNullException("exerciseId is a required property for DgCustomerCreateContractExerciseResponse and cannot be null");
            }
            this.ExerciseId = exerciseId;
        }

        /// <summary>
        /// Unique identifier for a DG exercise
        /// </summary>
        /// <value>Unique identifier for a DG exercise</value>
        /*
        <example>8ef454c6-74a5-48cf-972e-fac72d05e59c</example>
        */
        [DataMember(Name = "exercise_id", IsRequired = true, EmitDefaultValue = true)]
        public string ExerciseId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DgCustomerCreateContractExerciseResponse {\n");
            sb.Append("  ExerciseId: ").Append(ExerciseId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
