/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Com.Hopper.Hts.Airlines.Client.OpenAPIDateConverter;

namespace Com.Hopper.Hts.Airlines.Model
{
    /// <summary>
    /// Fare class of the segment
    /// </summary>
    /// <value>Fare class of the segment</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FareClass
    {
        /// <summary>
        /// Enum BasicEconomy for value: basic_economy
        /// </summary>
        [EnumMember(Value = "basic_economy")]
        BasicEconomy = 1,

        /// <summary>
        /// Enum Economy for value: economy
        /// </summary>
        [EnumMember(Value = "economy")]
        Economy = 2,

        /// <summary>
        /// Enum PremiumEconomy for value: premium_economy
        /// </summary>
        [EnumMember(Value = "premium_economy")]
        PremiumEconomy = 3,

        /// <summary>
        /// Enum Business for value: business
        /// </summary>
        [EnumMember(Value = "business")]
        Business = 4,

        /// <summary>
        /// Enum First for value: first
        /// </summary>
        [EnumMember(Value = "first")]
        First = 5
    }

}
