/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Hopper.Hts.Airlines.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Com.Hopper.Hts.Airlines.Model
{
    /// <summary>
    /// ModelOperatingSystem
    /// </summary>
    [JsonConverter(typeof(ModelOperatingSystemJsonConverter))]
    [DataContract(Name = "operating_system")]
    public partial class ModelOperatingSystem : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelOperatingSystem" /> class
        /// with the <see cref="Android" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Android.</param>
        public ModelOperatingSystem(Android actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelOperatingSystem" /> class
        /// with the <see cref="ChromeOs" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ChromeOs.</param>
        public ModelOperatingSystem(ChromeOs actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelOperatingSystem" /> class
        /// with the <see cref="IOs" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of IOs.</param>
        public ModelOperatingSystem(IOs actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelOperatingSystem" /> class
        /// with the <see cref="Linux" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Linux.</param>
        public ModelOperatingSystem(Linux actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelOperatingSystem" /> class
        /// with the <see cref="MacOs" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MacOs.</param>
        public ModelOperatingSystem(MacOs actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelOperatingSystem" /> class
        /// with the <see cref="OtherOs" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of OtherOs.</param>
        public ModelOperatingSystem(OtherOs actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelOperatingSystem" /> class
        /// with the <see cref="Windows" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Windows.</param>
        public ModelOperatingSystem(Windows actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(Android) || value is Android)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ChromeOs) || value is ChromeOs)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(IOs) || value is IOs)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(Linux) || value is Linux)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MacOs) || value is MacOs)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(OtherOs) || value is OtherOs)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(Windows) || value is Windows)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: Android, ChromeOs, IOs, Linux, MacOs, OtherOs, Windows");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `Android`. If the actual instance is not `Android`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Android</returns>
        public Android GetAndroid()
        {
            return (Android)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ChromeOs`. If the actual instance is not `ChromeOs`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ChromeOs</returns>
        public ChromeOs GetChromeOs()
        {
            return (ChromeOs)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `IOs`. If the actual instance is not `IOs`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of IOs</returns>
        public IOs GetIOs()
        {
            return (IOs)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Linux`. If the actual instance is not `Linux`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Linux</returns>
        public Linux GetLinux()
        {
            return (Linux)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MacOs`. If the actual instance is not `MacOs`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MacOs</returns>
        public MacOs GetMacOs()
        {
            return (MacOs)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `OtherOs`. If the actual instance is not `OtherOs`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of OtherOs</returns>
        public OtherOs GetOtherOs()
        {
            return (OtherOs)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Windows`. If the actual instance is not `Windows`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Windows</returns>
        public Windows GetWindows()
        {
            return (Windows)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelOperatingSystem {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ModelOperatingSystem.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ModelOperatingSystem
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ModelOperatingSystem</returns>
        public static ModelOperatingSystem FromJson(string jsonString)
        {
            ModelOperatingSystem newModelOperatingSystem = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newModelOperatingSystem;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Android).GetProperty("AdditionalProperties") == null)
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<Android>(jsonString, ModelOperatingSystem.SerializerSettings));
                }
                else
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<Android>(jsonString, ModelOperatingSystem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Android");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Android: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ChromeOs).GetProperty("AdditionalProperties") == null)
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<ChromeOs>(jsonString, ModelOperatingSystem.SerializerSettings));
                }
                else
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<ChromeOs>(jsonString, ModelOperatingSystem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ChromeOs");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ChromeOs: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(IOs).GetProperty("AdditionalProperties") == null)
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<IOs>(jsonString, ModelOperatingSystem.SerializerSettings));
                }
                else
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<IOs>(jsonString, ModelOperatingSystem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("IOs");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into IOs: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Linux).GetProperty("AdditionalProperties") == null)
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<Linux>(jsonString, ModelOperatingSystem.SerializerSettings));
                }
                else
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<Linux>(jsonString, ModelOperatingSystem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Linux");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Linux: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MacOs).GetProperty("AdditionalProperties") == null)
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<MacOs>(jsonString, ModelOperatingSystem.SerializerSettings));
                }
                else
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<MacOs>(jsonString, ModelOperatingSystem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MacOs");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MacOs: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(OtherOs).GetProperty("AdditionalProperties") == null)
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<OtherOs>(jsonString, ModelOperatingSystem.SerializerSettings));
                }
                else
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<OtherOs>(jsonString, ModelOperatingSystem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("OtherOs");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into OtherOs: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Windows).GetProperty("AdditionalProperties") == null)
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<Windows>(jsonString, ModelOperatingSystem.SerializerSettings));
                }
                else
                {
                    newModelOperatingSystem = new ModelOperatingSystem(JsonConvert.DeserializeObject<Windows>(jsonString, ModelOperatingSystem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Windows");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Windows: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newModelOperatingSystem;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ModelOperatingSystem
    /// </summary>
    public class ModelOperatingSystemJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ModelOperatingSystem).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return ModelOperatingSystem.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return ModelOperatingSystem.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
