/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DgContents
    /// </summary>
    [DataContract(Name = "dg_contents")]
    public partial class DgContents : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DgContents" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DgContents() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DgContents" /> class.
        /// </summary>
        /// <param name="bulletPoints">An array containing the bullet points to be displayed (required).</param>
        /// <param name="labels">labels (required).</param>
        public DgContents(List<string> bulletPoints = default(List<string>), Dictionary<string, string> labels = default(Dictionary<string, string>))
        {
            // to ensure "bulletPoints" is required (not null)
            if (bulletPoints == null)
            {
                throw new ArgumentNullException("bulletPoints is a required property for DgContents and cannot be null");
            }
            this.BulletPoints = bulletPoints;
            // to ensure "labels" is required (not null)
            if (labels == null)
            {
                throw new ArgumentNullException("labels is a required property for DgContents and cannot be null");
            }
            this.Labels = labels;
        }

        /// <summary>
        /// An array containing the bullet points to be displayed
        /// </summary>
        /// <value>An array containing the bullet points to be displayed</value>
        [DataMember(Name = "bullet_points", IsRequired = true, EmitDefaultValue = true)]
        public List<string> BulletPoints { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [DataMember(Name = "labels", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, string> Labels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DgContents {\n");
            sb.Append("  BulletPoints: ").Append(BulletPoints).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
