/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DgEvent
    /// </summary>
    [JsonConverter(typeof(DgEventJsonConverter))]
    [DataContract(Name = "dg_event")]
    public partial class DgEvent : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DgEvent" /> class
        /// with the <see cref="BookingConfirmed2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of BookingConfirmed2.</param>
        public DgEvent(BookingConfirmed2 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DgEvent" /> class
        /// with the <see cref="DgExerciseCallbackLaunched" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DgExerciseCallbackLaunched.</param>
        public DgEvent(DgExerciseCallbackLaunched actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DgEvent" /> class
        /// with the <see cref="DgExerciseCustomerDataComplete" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DgExerciseCustomerDataComplete.</param>
        public DgEvent(DgExerciseCustomerDataComplete actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DgEvent" /> class
        /// with the <see cref="DgExercisePortalComplete" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DgExercisePortalComplete.</param>
        public DgEvent(DgExercisePortalComplete actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DgEvent" /> class
        /// with the <see cref="DgExerciseVerificationComplete" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DgExerciseVerificationComplete.</param>
        public DgEvent(DgExerciseVerificationComplete actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(BookingConfirmed2) || value is BookingConfirmed2)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(DgExerciseCallbackLaunched) || value is DgExerciseCallbackLaunched)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(DgExerciseCustomerDataComplete) || value is DgExerciseCustomerDataComplete)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(DgExercisePortalComplete) || value is DgExercisePortalComplete)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(DgExerciseVerificationComplete) || value is DgExerciseVerificationComplete)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: BookingConfirmed2, DgExerciseCallbackLaunched, DgExerciseCustomerDataComplete, DgExercisePortalComplete, DgExerciseVerificationComplete");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `BookingConfirmed2`. If the actual instance is not `BookingConfirmed2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of BookingConfirmed2</returns>
        public BookingConfirmed2 GetBookingConfirmed2()
        {
            return (BookingConfirmed2)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DgExerciseCallbackLaunched`. If the actual instance is not `DgExerciseCallbackLaunched`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DgExerciseCallbackLaunched</returns>
        public DgExerciseCallbackLaunched GetDgExerciseCallbackLaunched()
        {
            return (DgExerciseCallbackLaunched)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DgExerciseCustomerDataComplete`. If the actual instance is not `DgExerciseCustomerDataComplete`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DgExerciseCustomerDataComplete</returns>
        public DgExerciseCustomerDataComplete GetDgExerciseCustomerDataComplete()
        {
            return (DgExerciseCustomerDataComplete)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DgExercisePortalComplete`. If the actual instance is not `DgExercisePortalComplete`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DgExercisePortalComplete</returns>
        public DgExercisePortalComplete GetDgExercisePortalComplete()
        {
            return (DgExercisePortalComplete)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DgExerciseVerificationComplete`. If the actual instance is not `DgExerciseVerificationComplete`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DgExerciseVerificationComplete</returns>
        public DgExerciseVerificationComplete GetDgExerciseVerificationComplete()
        {
            return (DgExerciseVerificationComplete)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DgEvent {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, DgEvent.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of DgEvent
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of DgEvent</returns>
        public static DgEvent FromJson(string jsonString)
        {
            DgEvent newDgEvent = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newDgEvent;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(BookingConfirmed2).GetProperty("AdditionalProperties") == null)
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<BookingConfirmed2>(jsonString, DgEvent.SerializerSettings));
                }
                else
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<BookingConfirmed2>(jsonString, DgEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("BookingConfirmed2");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into BookingConfirmed2: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DgExerciseCallbackLaunched).GetProperty("AdditionalProperties") == null)
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<DgExerciseCallbackLaunched>(jsonString, DgEvent.SerializerSettings));
                }
                else
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<DgExerciseCallbackLaunched>(jsonString, DgEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DgExerciseCallbackLaunched");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DgExerciseCallbackLaunched: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DgExerciseCustomerDataComplete).GetProperty("AdditionalProperties") == null)
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<DgExerciseCustomerDataComplete>(jsonString, DgEvent.SerializerSettings));
                }
                else
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<DgExerciseCustomerDataComplete>(jsonString, DgEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DgExerciseCustomerDataComplete");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DgExerciseCustomerDataComplete: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DgExercisePortalComplete).GetProperty("AdditionalProperties") == null)
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<DgExercisePortalComplete>(jsonString, DgEvent.SerializerSettings));
                }
                else
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<DgExercisePortalComplete>(jsonString, DgEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DgExercisePortalComplete");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DgExercisePortalComplete: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DgExerciseVerificationComplete).GetProperty("AdditionalProperties") == null)
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<DgExerciseVerificationComplete>(jsonString, DgEvent.SerializerSettings));
                }
                else
                {
                    newDgEvent = new DgEvent(JsonConvert.DeserializeObject<DgExerciseVerificationComplete>(jsonString, DgEvent.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DgExerciseVerificationComplete");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DgExerciseVerificationComplete: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newDgEvent;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for DgEvent
    /// </summary>
    public class DgEventJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(DgEvent).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return DgEvent.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return DgEvent.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
