/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Hopper.Hts.Airlines.Model;
using Com.Hopper.Hts.Airlines.Client;
using System.Reflection;

namespace Com.Hopper.Hts.Airlines.Test.Model
{
    /// <summary>
    ///  Class for testing AgentReseller
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentResellerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentReseller
        //private AgentReseller instance;

        public AgentResellerTests()
        {
            // TODO uncomment below to create an instance of AgentReseller
            //instance = new AgentReseller();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentReseller
        /// </summary>
        [Fact]
        public void AgentResellerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentReseller
            //Assert.IsType<AgentReseller>(instance);
        }

        /// <summary>
        /// Test the property 'AgencyId'
        /// </summary>
        [Fact]
        public void AgencyIdTest()
        {
            // TODO unit test for the property 'AgencyId'
        }

        /// <summary>
        /// Test the property 'AgentId'
        /// </summary>
        [Fact]
        public void AgentIdTest()
        {
            // TODO unit test for the property 'AgentId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
