/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Hopper.Hts.Airlines.Model;
using Com.Hopper.Hts.Airlines.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Hopper.Hts.Airlines.Test.Model
{
    /// <summary>
    ///  Class for testing CfarCreateExercisePassengerPricing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CfarCreateExercisePassengerPricingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CfarCreateExercisePassengerPricing
        //private CfarCreateExercisePassengerPricing instance;

        public CfarCreateExercisePassengerPricingTests()
        {
            // TODO uncomment below to create an instance of CfarCreateExercisePassengerPricing
            //instance = new CfarCreateExercisePassengerPricing();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CfarCreateExercisePassengerPricing
        /// </summary>
        [Fact]
        public void CfarCreateExercisePassengerPricingInstanceTest()
        {
            // TODO uncomment below to test "IsType" CfarCreateExercisePassengerPricing
            //Assert.IsType<CfarCreateExercisePassengerPricing>(instance);
        }

        /// <summary>
        /// Test the property 'PassengerCount'
        /// </summary>
        [Fact]
        public void PassengerCountTest()
        {
            // TODO unit test for the property 'PassengerCount'
        }

        /// <summary>
        /// Test the property 'IndividualPrice'
        /// </summary>
        [Fact]
        public void IndividualPriceTest()
        {
            // TODO unit test for the property 'IndividualPrice'
        }

        /// <summary>
        /// Test the property 'Taxes'
        /// </summary>
        [Fact]
        public void TaxesTest()
        {
            // TODO unit test for the property 'Taxes'
        }
    }
}
