/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Hopper.Hts.Airlines.Model;
using Com.Hopper.Hts.Airlines.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Hopper.Hts.Airlines.Test.Model
{
    /// <summary>
    ///  Class for testing CfarOfferLight
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CfarOfferLightTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CfarOfferLight
        //private CfarOfferLight instance;

        public CfarOfferLightTests()
        {
            // TODO uncomment below to create an instance of CfarOfferLight
            //instance = new CfarOfferLight();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CfarOfferLight
        /// </summary>
        [Fact]
        public void CfarOfferLightInstanceTest()
        {
            // TODO uncomment below to test "IsType" CfarOfferLight
            //Assert.IsType<CfarOfferLight>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Premium'
        /// </summary>
        [Fact]
        public void PremiumTest()
        {
            // TODO unit test for the property 'Premium'
        }

        /// <summary>
        /// Test the property 'CoveragePercentage'
        /// </summary>
        [Fact]
        public void CoveragePercentageTest()
        {
            // TODO unit test for the property 'CoveragePercentage'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'TermsConditionsUrl'
        /// </summary>
        [Fact]
        public void TermsConditionsUrlTest()
        {
            // TODO unit test for the property 'TermsConditionsUrl'
        }
    }
}
