/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Hopper.Hts.Airlines.Model;
using Com.Hopper.Hts.Airlines.Client;
using System.Reflection;

namespace Com.Hopper.Hts.Airlines.Test.Model
{
    /// <summary>
    ///  Class for testing CreateExternalCfarOfferRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateExternalCfarOfferRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateExternalCfarOfferRequest
        //private CreateExternalCfarOfferRequest instance;

        public CreateExternalCfarOfferRequestTests()
        {
            // TODO uncomment below to create an instance of CreateExternalCfarOfferRequest
            //instance = new CreateExternalCfarOfferRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateExternalCfarOfferRequest
        /// </summary>
        [Fact]
        public void CreateExternalCfarOfferRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateExternalCfarOfferRequest
            //Assert.IsType<CreateExternalCfarOfferRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }

        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'ToUsdExchangeRate'
        /// </summary>
        [Fact]
        public void ToUsdExchangeRateTest()
        {
            // TODO unit test for the property 'ToUsdExchangeRate'
        }

        /// <summary>
        /// Test the property 'PremiumTotalAmount'
        /// </summary>
        [Fact]
        public void PremiumTotalAmountTest()
        {
            // TODO unit test for the property 'PremiumTotalAmount'
        }

        /// <summary>
        /// Test the property 'PremiumPercentage'
        /// </summary>
        [Fact]
        public void PremiumPercentageTest()
        {
            // TODO unit test for the property 'PremiumPercentage'
        }

        /// <summary>
        /// Test the property 'PayoutTotalAmount'
        /// </summary>
        [Fact]
        public void PayoutTotalAmountTest()
        {
            // TODO unit test for the property 'PayoutTotalAmount'
        }

        /// <summary>
        /// Test the property 'PayoutPercentage'
        /// </summary>
        [Fact]
        public void PayoutPercentageTest()
        {
            // TODO unit test for the property 'PayoutPercentage'
        }

        /// <summary>
        /// Test the property 'TaxesTotal'
        /// </summary>
        [Fact]
        public void TaxesTotalTest()
        {
            // TODO unit test for the property 'TaxesTotal'
        }

        /// <summary>
        /// Test the property 'ContractExpiryDateTime'
        /// </summary>
        [Fact]
        public void ContractExpiryDateTimeTest()
        {
            // TODO unit test for the property 'ContractExpiryDateTime'
        }

        /// <summary>
        /// Test the property 'Itinerary'
        /// </summary>
        [Fact]
        public void ItineraryTest()
        {
            // TODO unit test for the property 'Itinerary'
        }

        /// <summary>
        /// Test the property 'MinMinutesDelay'
        /// </summary>
        [Fact]
        public void MinMinutesDelayTest()
        {
            // TODO unit test for the property 'MinMinutesDelay'
        }

        /// <summary>
        /// Test the property 'BookingDateTime'
        /// </summary>
        [Fact]
        public void BookingDateTimeTest()
        {
            // TODO unit test for the property 'BookingDateTime'
        }

        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }
    }
}
