/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Hopper.Hts.Airlines.Model;
using Com.Hopper.Hts.Airlines.Client;
using System.Reflection;

namespace Com.Hopper.Hts.Airlines.Test.Model
{
    /// <summary>
    ///  Class for testing DgContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DgContractTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DgContract
        //private DgContract instance;

        public DgContractTests()
        {
            // TODO uncomment below to create an instance of DgContract
            //instance = new DgContract();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DgContract
        /// </summary>
        [Fact]
        public void DgContractInstanceTest()
        {
            // TODO uncomment below to test "IsType" DgContract
            //Assert.IsType<DgContract>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Offers'
        /// </summary>
        [Fact]
        public void OffersTest()
        {
            // TODO unit test for the property 'Offers'
        }

        /// <summary>
        /// Test the property 'CoveragePercentage'
        /// </summary>
        [Fact]
        public void CoveragePercentageTest()
        {
            // TODO unit test for the property 'CoveragePercentage'
        }

        /// <summary>
        /// Test the property 'Coverage'
        /// </summary>
        [Fact]
        public void CoverageTest()
        {
            // TODO unit test for the property 'Coverage'
        }

        /// <summary>
        /// Test the property 'Premium'
        /// </summary>
        [Fact]
        public void PremiumTest()
        {
            // TODO unit test for the property 'Premium'
        }

        /// <summary>
        /// Test the property 'ServiceCap'
        /// </summary>
        [Fact]
        public void ServiceCapTest()
        {
            // TODO unit test for the property 'ServiceCap'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'TaxesTotal'
        /// </summary>
        [Fact]
        public void TaxesTotalTest()
        {
            // TODO unit test for the property 'TaxesTotal'
        }

        /// <summary>
        /// Test the property 'MaxHoursBeforeDeparture'
        /// </summary>
        [Fact]
        public void MaxHoursBeforeDepartureTest()
        {
            // TODO unit test for the property 'MaxHoursBeforeDeparture'
        }

        /// <summary>
        /// Test the property 'MinMinutesDelay'
        /// </summary>
        [Fact]
        public void MinMinutesDelayTest()
        {
            // TODO unit test for the property 'MinMinutesDelay'
        }

        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Fact]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }

        /// <summary>
        /// Test the property 'ExpiryDateTime'
        /// </summary>
        [Fact]
        public void ExpiryDateTimeTest()
        {
            // TODO unit test for the property 'ExpiryDateTime'
        }

        /// <summary>
        /// Test the property 'ExtAttributes'
        /// </summary>
        [Fact]
        public void ExtAttributesTest()
        {
            // TODO unit test for the property 'ExtAttributes'
        }

        /// <summary>
        /// Test the property 'Taxes'
        /// </summary>
        [Fact]
        public void TaxesTest()
        {
            // TODO unit test for the property 'Taxes'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'PnrReference'
        /// </summary>
        [Fact]
        public void PnrReferenceTest()
        {
            // TODO unit test for the property 'PnrReference'
        }
    }
}
