/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Hopper.Hts.Airlines.Model;
using Com.Hopper.Hts.Airlines.Client;
using System.Reflection;

namespace Com.Hopper.Hts.Airlines.Test.Model
{
    /// <summary>
    ///  Class for testing DgOffersBannerLoaded
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DgOffersBannerLoadedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DgOffersBannerLoaded
        //private DgOffersBannerLoaded instance;

        public DgOffersBannerLoadedTests()
        {
            // TODO uncomment below to create an instance of DgOffersBannerLoaded
            //instance = new DgOffersBannerLoaded();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DgOffersBannerLoaded
        /// </summary>
        [Fact]
        public void DgOffersBannerLoadedInstanceTest()
        {
            // TODO uncomment below to test "IsType" DgOffersBannerLoaded
            //Assert.IsType<DgOffersBannerLoaded>(instance);
        }

        /// <summary>
        /// Test the property 'OccurredDateTime'
        /// </summary>
        [Fact]
        public void OccurredDateTimeTest()
        {
            // TODO unit test for the property 'OccurredDateTime'
        }

        /// <summary>
        /// Test the property 'DgOfferIds'
        /// </summary>
        [Fact]
        public void DgOfferIdsTest()
        {
            // TODO unit test for the property 'DgOfferIds'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
