/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Hopper.Hts.Airlines.Model;
using Com.Hopper.Hts.Airlines.Client;
using System.Reflection;

namespace Com.Hopper.Hts.Airlines.Test.Model
{
    /// <summary>
    ///  Class for testing ExerciseStepResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExerciseStepResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExerciseStepResult
        //private ExerciseStepResult instance;

        public ExerciseStepResultTests()
        {
            // TODO uncomment below to create an instance of ExerciseStepResult
            //instance = new ExerciseStepResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExerciseStepResult
        /// </summary>
        [Fact]
        public void ExerciseStepResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExerciseStepResult
            //Assert.IsType<ExerciseStepResult>(instance);
        }
    }
}
