/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Hopper.Hts.Airlines.Model;
using Com.Hopper.Hts.Airlines.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Hopper.Hts.Airlines.Test.Model
{
    /// <summary>
    ///  Class for testing FareRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FareRuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FareRule
        //private FareRule instance;

        public FareRuleTests()
        {
            // TODO uncomment below to create an instance of FareRule
            //instance = new FareRule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FareRule
        /// </summary>
        [Fact]
        public void FareRuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" FareRule
            //Assert.IsType<FareRule>(instance);
        }

        /// <summary>
        /// Test the property 'ModificationType'
        /// </summary>
        [Fact]
        public void ModificationTypeTest()
        {
            // TODO unit test for the property 'ModificationType'
        }

        /// <summary>
        /// Test the property 'ModificationTime'
        /// </summary>
        [Fact]
        public void ModificationTimeTest()
        {
            // TODO unit test for the property 'ModificationTime'
        }

        /// <summary>
        /// Test the property 'Allowed'
        /// </summary>
        [Fact]
        public void AllowedTest()
        {
            // TODO unit test for the property 'Allowed'
        }

        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }

        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Fact]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }

        /// <summary>
        /// Test the property 'RefundMethod'
        /// </summary>
        [Fact]
        public void RefundMethodTest()
        {
            // TODO unit test for the property 'RefundMethod'
        }
    }
}
