/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Com.Hopper.Hts.Airlines.Client;
using Com.Hopper.Hts.Airlines.Api;
// uncomment below to import models
//using Com.Hopper.Hts.Airlines.Model;

namespace Com.Hopper.Hts.Airlines.Test.Api
{
    /// <summary>
    ///  Class for testing SessionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SessionsApiTests : IDisposable
    {
        private SessionsApi instance;

        public SessionsApiTests()
        {
            instance = new SessionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SessionsApi
            //Assert.IsType<SessionsApi>(instance);
        }

        /// <summary>
        /// Test PostSessions
        /// </summary>
        [Fact]
        public void PostSessionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateAirlineSessionRequest createAirlineSessionRequest = null;
            //var response = instance.PostSessions(createAirlineSessionRequest);
            //Assert.IsType<AirlineSession>(response);
        }
    }
}
