/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAirlineCfarSessionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAirlineCfarSessionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAirlineCfarSessionRequest
        //private CreateAirlineCfarSessionRequest instance;

        public CreateAirlineCfarSessionRequestTests()
        {
            // TODO uncomment below to create an instance of CreateAirlineCfarSessionRequest
            //instance = new CreateAirlineCfarSessionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAirlineCfarSessionRequest
        /// </summary>
        [Fact]
        public void CreateAirlineCfarSessionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAirlineCfarSessionRequest
            //Assert.IsType<CreateAirlineCfarSessionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'UserInfo'
        /// </summary>
        [Fact]
        public void UserInfoTest()
        {
            // TODO unit test for the property 'UserInfo'
        }

        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }

        /// <summary>
        /// Test the property 'PointOfSale'
        /// </summary>
        [Fact]
        public void PointOfSaleTest()
        {
            // TODO unit test for the property 'PointOfSale'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
    }
}
