/*
 * Airline API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DgItinerary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DgItineraryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DgItinerary
        //private DgItinerary instance;

        public DgItineraryTests()
        {
            // TODO uncomment below to create an instance of DgItinerary
            //instance = new DgItinerary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DgItinerary
        /// </summary>
        [Fact]
        public void DgItineraryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DgItinerary
            //Assert.IsType<DgItinerary>(instance);
        }

        /// <summary>
        /// Test the property 'PassengerPricing'
        /// </summary>
        [Fact]
        public void PassengerPricingTest()
        {
            // TODO unit test for the property 'PassengerPricing'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Slices'
        /// </summary>
        [Fact]
        public void SlicesTest()
        {
            // TODO unit test for the property 'Slices'
        }

        /// <summary>
        /// Test the property 'Ancillaries'
        /// </summary>
        [Fact]
        public void AncillariesTest()
        {
            // TODO unit test for the property 'Ancillaries'
        }

        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Fact]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }

        /// <summary>
        /// Test the property 'Passengers'
        /// </summary>
        [Fact]
        public void PassengersTest()
        {
            // TODO unit test for the property 'Passengers'
        }
    }
}
